export const MedStatementFields = [
    "name",
    "surname",
    "patronymic",
    "birthday",
    "address",
    "job",
    "hospitalizationDate",
    "dischargeDate",
    "mainDiagnosis",
    "complicationsDiagnosis",
    "relatedDiagnosis",
    "complaints",
    "medicalHistory",
    "KT",
    "MRT",
    "FBC",
    "FEGDC",
    "histology",
    "MDKDecision",
    "PT_PHTOperation",
    "recommendations",
    "date",
    "doctor",
] as const;
