import { Fields } from "../types/SchemaFactory";
import { MedStatementModel } from "../types/models/MedStatement";
import { schemaFactory } from "./SchemaFactory";

export const medStatementFields: Fields<MedStatementModel> = {
    name: {
        min: 2,
        max: 100,
        placeholder: "Ім'я",
        initial: "",
        type: "text",
    },
    surname: {
        min: 2,
        max: 100,
        placeholder: "Прізвище",
        initial: "",
        type: "text",
    },
    patronymic: {
        min: 2,
        max: 100,
        placeholder: "По батькові",
        initial: "",
        type: "text",
    },
    birthday: {
        min: 2,
        max: 100,
        placeholder: "Дата народження",
        initial: "",
        type: "date",
    },
    address: {
        min: 2,
        max: 100,
        placeholder: "Місце проживання",
        initial: "",
        type: "text",
    },
    job: {
        min: 2,
        max: 100,
        placeholder: "Місце роботи",
        initial: "",
        type: "text",
    },
    hospitalizationDate: {
        min: 2,
        max: 100,
        placeholder: "Дата госпіталізації",
        initial: "",
        type: "date",
    },
    dischargeDate: {
        min: 2,
        max: 100,
        placeholder: "Дата вибуття зі стаціонару",
        initial: "",
        type: "date",
    },
    mainDiagnosis: {
        min: 2,
        max: 100,
        placeholder: "Основний діагноз",
        initial: "",
        type: "text",
    },
    complicationsDiagnosis: {
        min: 2,
        max: 100,
        placeholder: "Ускладнення (діагноз)",
        initial: "",
        type: "text",
    },
    relatedDiagnosis: {
        min: 2,
        max: 100,
        placeholder: "Супутній діагноз",
        initial: "",
        type: "text",
    },
    complaints: {
        min: 2,
        max: 100,
        placeholder: "Скарги",
        initial: "",
        type: "text",
    },
    medicalHistory: {
        min: 2,
        max: 100,
        placeholder: "Анамнез хвороби",
        initial: "",
        type: "text",
    },
    KT: {
        min: 2,
        max: 100,
        placeholder: "КТ ОГК, ОБП, ОМТ, ГМ",
        initial: "",
        type: "text",
    },
    MRT: {
        min: 2,
        max: 100,
        placeholder: "МРТ ГМ",
        initial: "",
        type: "text",
    },
    FBC: {
        min: 2,
        max: 100,
        placeholder: "ФБС",
        initial: "",
        type: "text",
    },
    FEGDC: {
        min: 2,
        max: 100,
        placeholder: "ФЕГДС",
        initial: "",
        type: "text",
    },
    histology_cytology: {
        min: 2,
        max: 100,
        placeholder: "Гістологія/цитологія",
        initial: "",
        type: "text",
    },
    MDKDecision: {
        min: 2,
        max: 100,
        placeholder: "Рішення МДК",
        initial: "",
        type: "text",
    },
    PT_PHTOperation: {
        min: 2,
        max: 100,
        placeholder: "Операція / ПТ / ПХТ",
        initial: "",
        type: "text",
    },
    recommendations: {
        min: 2,
        max: 100,
        placeholder: "Лікувальні і трудові рекомендації",
        initial: "",
        type: "text",
    },
    date: {
        min: 2,
        max: 100,
        placeholder: "Дата",
        initial: "",
        type: "date",
    },
    treatingDoctor: {
        min: 2,
        max: 100,
        placeholder: "Лікуючий лікар",
        initial: "",
        type: "text",
    },
};

export const medStatementSchema = schemaFactory(medStatementFields);
